version: "3.7"
services:
  postgres:
    build: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-gces:/var/lib/postgresql/data

  backend:
    build: library_back
    ports:
      - 8000:8000
    env_file:
      - ./library_back/.env
    depends_on:
      - postgres

  frontend:
    build: library_front
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - backend

volumes:
  postgres-gces:
